# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "email-automation"
client_id = "25857dad7be5378e4b51382635d110f3"
application_url = "https://flyer-boats-extras-estimates.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_customers"

[auth]
redirect_urls = [
  "https://flyer-boats-extras-estimates.trycloudflare.com/auth/callback",
  "https://flyer-boats-extras-estimates.trycloudflare.com/auth/shopify/callback",
  "https://flyer-boats-extras-estimates.trycloudflare.com/api/auth/callback",
  "https://flyer-boats-extras-estimates.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tmt-email-automation.myshopify.com"
